### ISSUE TITLE
Mod crashes game

### ISSUE THREAD

**Issue by tacotexmex** [pithydon/falling_nodes#1]
Set a node def to include `falling_sticky_node = 1`, ran game, crashes:

`ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'falling_nodes' in callback node_on_dig(): ...minetest/mods/falling_nodes/init.lua:77: attempt to call global 'spawn_falling_node' (a nil value)`

**Comment by pithydon** [comment]
I haven't gotten around to porting this to minetest 5.

**Comment by tacotexmex** [comment]
Ah, I see. I was looking to implement something similar to [clumpfall](https://github.com/Noodlemire/clumpfall)…

**Comment by pithydon** [comment]
This mod is now ported to Minetest 5.
