### ISSUE TITLE
Make number touching node faces configurable in falling_sticky_node

### ISSUE THREAD

**Issue by tacotexmex** [pithydon/falling_nodes#2]
I'd like a more configurable falling_sticky_node feature where the group rating reflects the number of node faces needing to touch the node to support it.

So for example, for a node needing 3 touching faces the def would be:
```
groups = { falling_sticky_node = 3 }
```

Interesting, yes?

**Comment by pithydon** [comment]
Done

**Comment by tacotexmex** [comment]
Yesss 🌮👍
